import { describe, expect, it } from 'vitest'
import { groupIntoRuns } from '../engine/logGrouping'
import type { LogEntry } from '../state/types'

function entry(overrides: Partial<LogEntry> & Pick<LogEntry, 'id' | 'minute'>): LogEntry {
  return { type: 'action', summary: '', ...overrides }
}

describe('groupIntoRuns', () => {
  it('returns an empty array for an empty input', () => {
    expect(groupIntoRuns([])).toEqual([])
  })

  it('puts every entry in its own run when none are auto-charted', () => {
    const entries = [
      entry({ id: 'a', minute: 0 }),
      entry({ id: 'b', minute: 5 }),
      entry({ id: 'c', minute: 10 }),
    ]
    const runs = groupIntoRuns(entries)
    expect(runs.length).toBe(entries.length)
    expect(runs).toEqual([[entries[0]], [entries[1]], [entries[2]]])
  })

  it('collapses a consecutive run of auto-charted entries into one group', () => {
    const entries = [
      entry({ id: 'a', minute: 0, autoGeneratedByMultiStep: true }),
      entry({ id: 'b', minute: 1, autoGeneratedByMultiStep: true }),
      entry({ id: 'c', minute: 2, autoGeneratedByMultiStep: true }),
    ]
    const runs = groupIntoRuns(entries)
    expect(runs).toEqual([entries])
  })

  it('splits separate single-entry runs around an auto-charted batch', () => {
    const before = entry({ id: 'before', minute: 0 })
    const batch = [
      entry({ id: 'b1', minute: 1, autoGeneratedByMultiStep: true }),
      entry({ id: 'b2', minute: 2, autoGeneratedByMultiStep: true }),
    ]
    const after = entry({ id: 'after', minute: 3 })
    const runs = groupIntoRuns([before, ...batch, after])
    expect(runs).toEqual([[before], batch, [after]])
  })

  it('groups action and documentation entries together as one run when both are auto-charted, regardless of type', () => {
    const entries = [
      entry({ id: 'action-1', minute: 1, type: 'action', doseAction: 'titrate', autoGeneratedByMultiStep: true }),
      entry({ id: 'doc-1', minute: 1, type: 'documentation', location: 'iView', autoGeneratedByMultiStep: true }),
      entry({ id: 'action-2', minute: 2, type: 'action', doseAction: 'titrate', autoGeneratedByMultiStep: true }),
      entry({ id: 'doc-2', minute: 2, type: 'documentation', location: 'iView', autoGeneratedByMultiStep: true }),
    ]
    const runs = groupIntoRuns(entries)
    expect(runs.length).toBe(1)
    expect(runs[0]).toEqual(entries)
  })
})
