import type { LogEntry } from '../state/types'

/**
 * Groups a chronological LogEntry list into "runs" — a consecutive stretch of
 * autoGeneratedByMultiStep entries (e.g. the paired action+documentation rows a single
 * "Apply these steps" click can generate, dozens at a time) collapses into one run;
 * every other entry is its own single-entry run. Pure — used by both
 * TitrationTimeline.tsx (titration-only view) and DocumentationReview.tsx (full
 * interleaved action+documentation view) so the two can't drift on what counts as an
 * auto-charted batch. Entries must already be sorted chronologically by the caller.
 */
export function groupIntoRuns(entries: LogEntry[]): LogEntry[][] {
  const runs: LogEntry[][] = []
  let i = 0
  while (i < entries.length) {
    const entry = entries[i]
    if (entry.autoGeneratedByMultiStep) {
      const batch = [entry]
      let j = i + 1
      while (j < entries.length && entries[j].autoGeneratedByMultiStep) {
        batch.push(entries[j])
        j++
      }
      runs.push(batch)
      i = j
    } else {
      runs.push([entry])
      i++
    }
  }
  return runs
}
