/**
 * Debrief scoring (BUILD_BRIEF §7 / §9.6): aggregates the sim session's log into a
 * scorecard — order adherence, interval/increment compliance, agent sequencing, BCMA/
 * I-TRACE verification, documentation cadence + placement, and provider-notification
 * correctness — plus a non-punitive coaching summary (CLAUDE.md: never present an
 * unsafe/off-order action as correct, but never punitive either).
 *
 * Pure — no store coupling; scoreSession() takes a plain snapshot of the relevant
 * SimState fields (structurally compatible with useSimStore.getState()).
 *
 * NOT scored here: weight-based dosing correctness (a static engine property already
 * covered by formulary.test.ts, not a per-session learner behavior).
 */
import { buildCadenceStatusForOrders } from './documentation'
import { SKILL_SIGNOFF_CRITERIA } from '../data/policy'
import type { BlockOfChartingRecord, Infusion, LogEntry, Order } from '../state/types'

export interface ScoringInput {
  orders: Order[]
  infusions: Infusion[]
  log: LogEntry[]
  verificationFlags: Record<string, boolean>
  adherenceFlags: Record<string, boolean>
  blockOfChartingHistory: BlockOfChartingRecord[]
}

export type ScoreStatus = 'met' | 'partial' | 'missed' | 'n/a'

export interface ScoreCategory {
  key: string
  label: string
  status: ScoreStatus
  detail: string
}

export interface Scorecard {
  categories: ScoreCategory[]
  /** 0-100 mean over non-n/a categories (met=100, partial=50, missed=0); null if nothing was scoreable yet. */
  overallPercent: number | null
  strengths: string[]
  opportunities: string[]
}

function statusFor(part: number, total: number): ScoreStatus {
  if (total === 0) return 'n/a'
  if (part === total) return 'met'
  if (part === 0) return 'missed'
  return 'partial'
}

function hasOwn(record: Record<string, boolean>, id: string): boolean {
  return Object.prototype.hasOwnProperty.call(record, id)
}

export function scoreSession(input: ScoringInput): Scorecard {
  const { orders, infusions, log, verificationFlags, adherenceFlags, blockOfChartingHistory } = input
  const doseEntries = log.filter((e) => e.type === 'action' && e.doseAction != null)
  // Order-compliance is deliberately bypassed under an active Block of Charting (CP
  // 4-156's emergent pathway — see store.ts's submitDose) — those entries were never
  // evaluated against the order, so grading them here would be meaningless. They're
  // accounted for separately in category 7 below instead. Entries auto-generated by a
  // multi-step titration plan (see runMultiStepTitration) are correct-by-construction,
  // not a demonstrated learner skill, so they're excluded here too — but category 5
  // (documentation cadence) deliberately keeps reading unfiltered doseEntries below,
  // since the plan's auto-charted entries are real charted assessments.
  const normalDoseEntries = doseEntries.filter((e) => !e.underBlockOfCharting && !e.autoGeneratedByMultiStep)
  const categories: ScoreCategory[] = []

  // 1. Order adherence — every initiate/titrate attempt, applied or not. Reads
  // adherenceFlags (order-compliance at attempt time) rather than outcome === 'applied',
  // so a training-mode override or validation-mode silent apply — which reach the
  // infusion despite being off-order — correctly stay out of "met" while still counting
  // in the denominator.
  {
    const applied = normalDoseEntries.filter((e) => adherenceFlags[e.id]).length
    categories.push({
      key: 'adherence',
      label: 'Order adherence',
      status: statusFor(applied, normalDoseEntries.length),
      detail:
        normalDoseEntries.length === 0
          ? 'No dose entries were made.'
          : `${applied} of ${normalDoseEntries.length} dose entries applied exactly as ordered.`,
    })
  }

  // 2. Interval & increment compliance — titrations only ("initiate" has no increment/interval).
  {
    const titrations = normalDoseEntries.filter((e) => e.doseAction === 'titrate')
    const compliant = titrations.filter((e) => !e.violations?.intervalTooSoon && !e.violations?.wrongIncrement).length
    categories.push({
      key: 'intervalIncrement',
      label: 'Titration interval & increment',
      status: statusFor(compliant, titrations.length),
      detail:
        titrations.length === 0
          ? 'No titrations were attempted.'
          : compliant === titrations.length
            ? `All ${titrations.length} titration(s) matched the ordered increment and interval.`
            : `${titrations.length - compliant} of ${titrations.length} titration(s) used an incorrect increment or came sooner than the ordered interval.`,
    })
  }

  // 3. Agent sequencing — never reaches "missed": the order/Guardrails check hard-blocks
  // it, so an attempted violation is a knowledge gap to flag, not harm that occurred.
  {
    const sequencedOrders = orders.filter((o) => o.sequence > 1)
    const sequenceAttempts = doseEntries.filter((e) => e.violations?.sequenceNotActivated)
    // n/a both when the scenario has no multi-agent structure to violate, AND when
    // nothing has been attempted yet at all — otherwise "no actions taken" would
    // misleadingly score as "met" here while every other category correctly shows n/a.
    const noActivityYet = doseEntries.length === 0
    categories.push({
      key: 'sequencing',
      label: 'Agent sequencing',
      status:
        sequencedOrders.length === 0 || noActivityYet
          ? 'n/a'
          : sequenceAttempts.length === 0
            ? 'met'
            : 'partial',
      detail:
        sequencedOrders.length === 0
          ? 'This scenario has a single agent — no sequencing to assess.'
          : noActivityYet
            ? 'No actions were taken yet.'
            : sequenceAttempts.length === 0
              ? 'No attempt was made to start a later agent before its activation condition was met.'
              : `${sequenceAttempts.length} attempt(s) to start or titrate a later agent before its activation condition was met — correctly blocked, not applied.`,
    })
  }

  // 4. BCMA / I-TRACE verification. Vasoactives are NOT high-alert at this institution
  // (see CLAUDE.md) — this is single-nurse verification, not an independent two-nurse
  // double-check. `verificationFlags` is only ever set for Begin Bag / dose-entry
  // actions (never provider notifications or charting), so membership alone identifies
  // the verifiable actions without any string matching.
  {
    const verifiable = log.filter((e) => e.type === 'action' && hasOwn(verificationFlags, e.id))
    const verified = verifiable.filter((e) => verificationFlags[e.id]).length
    categories.push({
      key: 'verification',
      label: 'BCMA / I-TRACE verification',
      status: statusFor(verified, verifiable.length),
      detail:
        verifiable.length === 0
          ? 'No actions requiring verification were taken.'
          : `${verified} of ${verifiable.length} actions had BCMA + I-TRACE verification confirmed before programming.`,
    })
  }

  // 5. Documentation cadence & placement. Placement is structurally enforced by the UI
  // (see engine/documentation.ts's doc comment) so only cadence can actually vary by
  // learner behavior — one iView charting satisfies every infusion's pending checkpoint
  // at that moment, since it documents the whole patient, not one drug.
  {
    const chartedMinutes = log.filter((e) => e.type === 'documentation' && e.location === 'iView').map((e) => e.minute)
    const allChecks = buildCadenceStatusForOrders(orders, infusions, doseEntries, chartedMinutes).flatMap((s) => s.checks)
    const met = allChecks.filter((c) => c.met).length
    categories.push({
      key: 'documentation',
      label: 'Documentation cadence & placement',
      status: statusFor(met, allChecks.length),
      detail:
        allChecks.length === 0
          ? 'No infusion was started, so no documentation was due.'
          : `${met} of ${allChecks.length} required checkpoints were charted (MAR/iView placement is system-enforced and always correct).`,
    })
  }

  // 6. Provider notification correctness. Covers two independent triggers: the
  // hard-stop needs-provider outcome (dose exceeds order max, target unmet), and the
  // softer early-notification checkpoint (order.earlyNotificationThreshold newly
  // crossed, target still unmet) — same satisfied-by-later-notification check for both.
  {
    const neededEvents = doseEntries.filter((e) => e.outcome === 'needs-provider' || e.earlyNotificationDue)
    const notifications = log.filter((e) => e.isProviderNotification)
    const satisfied = neededEvents.filter((e) =>
      notifications.some((n) => n.orderId === e.orderId && n.minute >= e.minute),
    ).length
    categories.push({
      key: 'providerNotification',
      label: 'Provider notification',
      status: statusFor(satisfied, neededEvents.length),
      detail:
        neededEvents.length === 0
          ? 'No situation requiring provider notification came up.'
          : `${satisfied} of ${neededEvents.length} provider-notification requirements were followed by an actual notification.`,
    })
  }

  // 7. Block of Charting documentation (CP 4-156's emergent rapid-titration pathway).
  // Minimal state (just start/end minute) is enough — physiological-parameters-evaluated
  // is derived from whether any iView charting fell inside the block's window, and
  // provider notification from whether a notification followed the block's start.
  {
    const chartedMinutes = log.filter((e) => e.type === 'documentation' && e.location === 'iView').map((e) => e.minute)
    const notifications = log.filter((e) => e.isProviderNotification)
    const compliant = blockOfChartingHistory.filter((block) => {
      const chartedDuring = chartedMinutes.some((m) => m >= block.startMinute && m <= (block.endMinute ?? Infinity))
      const providerNotified = notifications.some((n) => n.orderId === block.orderId && n.minute >= block.startMinute)
      return chartedDuring && providerNotified
    }).length
    categories.push({
      key: 'blockOfCharting',
      label: 'Block of Charting documentation',
      status: statusFor(compliant, blockOfChartingHistory.length),
      detail:
        blockOfChartingHistory.length === 0
          ? 'No Block of Charting episode occurred this session.'
          : `${compliant} of ${blockOfChartingHistory.length} Block of Charting episode(s) had parameters charted and the provider notified.`,
    })
  }

  // 8. Weaning sequence — never "missed", mirroring category 3's framing: a submitDose-path
  // attempt is hard-blocked by evaluateTitration (a knowledge gap, not harm that occurred),
  // and a discontinueInfusion-path violation is retroactive-only (discontinue stays
  // ungated) so it genuinely can't be "blocked" either — both stay "partial", not "missed".
  // Sourced from `log` broadly, not `doseEntries`, since discontinueInfusion entries carry
  // no `doseAction`.
  {
    const weanedOrders = orders.filter((o) => o.weanOrder != null)
    const weanAttempts = log.filter((e) => e.type === 'action' && e.violations?.wrongWeanOrder)
    const noActivityYet = log.filter((e) => e.type === 'action').length === 0
    categories.push({
      key: 'weaning',
      label: 'Weaning sequence',
      status: weanedOrders.length === 0 || noActivityYet ? 'n/a' : weanAttempts.length === 0 ? 'met' : 'partial',
      detail:
        weanedOrders.length === 0
          ? 'This scenario has no weaning-order requirement to assess.'
          : noActivityYet
            ? 'No actions were taken yet.'
            : weanAttempts.length === 0
              ? 'No down-titration or discontinuation was attempted before a lower-weanOrder agent was cleared.'
              : `${weanAttempts.length} down-titration/discontinuation attempt(s) occurred before a lower-weanOrder agent was cleared.`,
    })
  }

  // 9. Clinical judgment (Phase 18) — every resolved "what's your next move" decision
  // point, graded off the marker LogEntry chooseDecisionOption appends per pick (see
  // state/store.ts). `good` counts toward "met"; `caution`/`critical` don't, but a mix
  // still reads as `partial` (not `missed`) via the same statusFor() semantics every
  // other category uses — one questionable pick among several good ones shouldn't read
  // the same as a session with no sound judgment at all.
  {
    const decisions = log.filter((e) => e.decisionTone != null)
    const good = decisions.filter((e) => e.decisionTone === 'good').length
    categories.push({
      key: 'clinicalJudgment',
      label: 'Clinical judgment',
      status: statusFor(good, decisions.length),
      detail:
        decisions.length === 0
          ? 'This scenario had no decision points to assess.'
          : `${good} of ${decisions.length} decision(s) chose an option within your current orders.`,
    })
  }

  const scored = categories.filter((c) => c.status !== 'n/a')
  const overallPercent =
    scored.length === 0
      ? null
      : Math.round(
          (scored.reduce((sum, c) => sum + (c.status === 'met' ? 1 : c.status === 'partial' ? 0.5 : 0), 0) /
            scored.length) *
            100,
        )

  const strengths = categories.filter((c) => c.status === 'met').map((c) => `${c.label}: ${c.detail}`)
  const opportunities = categories
    .filter((c) => c.status === 'partial' || c.status === 'missed')
    .map((c) => `${c.label}: ${c.detail}`)

  return { categories, overallPercent, strengths, opportunities }
}

/**
 * Automatic pass/fail for the skill sign-off requirement (Phase 15) — see
 * data/policy.ts's SKILL_SIGNOFF_CRITERIA for the threshold/reasoning. Pure over a
 * Scorecard alone; this function has no notion of SimMode — callers (see
 * engine/skillAttempt.ts's buildAttemptRecord) are responsible for only treating the
 * result as "meets the requirement" for a validation-mode debrief.
 */
export function isSkillPassed(card: Scorecard): boolean {
  if (card.overallPercent == null) return false
  if (card.overallPercent < SKILL_SIGNOFF_CRITERIA.minOverallPercent) return false
  if (SKILL_SIGNOFF_CRITERIA.requireNoMissedCategory && card.categories.some((c) => c.status === 'missed')) {
    return false
  }
  return true
}
