import { useState } from 'react'
import { Panel } from '../design/primitives'
import { getDrug } from '../data/formulary'
import { vitalsAtMinute, type VitalsHistoryPoint } from '../engine/vitalsAtMinute'
import { formatClock } from '../lib/time'
import type { LogEntry } from '../state/types'

export interface TitrationVitalsHistoryProps {
  log: LogEntry[]
  vitalsHistory: VitalsHistoryPoint[]
}

/**
 * Phase 18's real, ungrouped titration + vitals history — every applied dose entry as
 * its own row, joined with the vitals in effect at that moment (vitalsAtMinute). This
 * is deliberately a NEW, separate component, not a modification of TitrationTimeline.tsx
 * (which keeps its own retrospective-charting purpose) — and explicitly bypasses that
 * file's groupIntoRuns batching, per the user's direct instruction that the real
 * history should show every individual titration, not summarized/collapsed runs, with
 * no "guided"/batching language anywhere in the UI. Collapsed by default (a long
 * session can have many rows); the toggle label names the real count.
 */
export function TitrationVitalsHistory({ log, vitalsHistory }: TitrationVitalsHistoryProps) {
  const [open, setOpen] = useState(false)
  const entries = log
    .filter((e) => e.type === 'action' && e.doseAction != null && e.outcome === 'applied')
    .sort((a, b) => a.minute - b.minute)

  return (
    <Panel title="Titration & vitals history" subtitle="Every real titration this session, with the vitals in effect at that moment.">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between text-sm font-medium text-cardinal"
        aria-expanded={open}
      >
        <span>
          {open ? 'Hide' : 'Show'} history ({entries.length} entr{entries.length === 1 ? 'y' : 'ies'})
        </span>
        <span aria-hidden="true">{open ? '▾' : '▸'}</span>
      </button>
      {open && (
        <div className="mt-3 overflow-x-auto">
          {entries.length === 0 ? (
            <p className="text-sm text-muted">No titrations yet this session.</p>
          ) : (
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="border-b border-border text-left text-xs font-semibold tracking-wide text-muted uppercase">
                  <th className="py-1.5 pr-3">Time</th>
                  <th className="py-1.5 pr-3">Event</th>
                  <th className="py-1.5 pr-3">MAP</th>
                  <th className="py-1.5 pr-3">HR</th>
                  <th className="py-1.5 pr-3">SpO2</th>
                </tr>
              </thead>
              <tbody>
                {entries.map((entry, i) => {
                  const drug = entry.drugId ? getDrug(entry.drugId) : null
                  const vitals = vitalsAtMinute(vitalsHistory, entry.minute)
                  return (
                    <tr key={entry.id} className={i % 2 === 1 ? 'bg-bg' : undefined}>
                      <td className="py-1.5 pr-3 font-mono text-muted">{formatClock(entry.minute)}</td>
                      <td className="py-1.5 pr-3 text-ink">
                        {entry.doseAction === 'initiate' ? 'Initiate' : 'Titrate'} {drug?.name ?? ''} to {entry.dose} {drug?.unit ?? ''}
                        {entry.autoGeneratedByMultiStep && <span className="ml-1 text-xs text-muted">(auto-charted)</span>}
                      </td>
                      <td className="py-1.5 pr-3 font-mono text-ink">{vitals ? vitals.map : '—'}</td>
                      <td className="py-1.5 pr-3 font-mono text-ink">{vitals ? vitals.hr : '—'}</td>
                      <td className="py-1.5 pr-3 font-mono text-ink">{vitals ? vitals.spo2 : '—'}</td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          )}
        </div>
      )}
    </Panel>
  )
}
