import { useState } from 'react'
import { Button, Panel } from '../design/primitives'
import { getDrug } from '../data/formulary'
import { buildCadenceStatusForOrders } from '../engine/documentation'
import { formatClock } from '../lib/time'
import type { Infusion, LogEntry, Order, VitalSigns } from '../state/types'

export interface TitrationTimelineProps {
  log: LogEntry[]
  vitalsHistory: { minute: number; vitals: VitalSigns }[]
  orders: Order[]
  infusions: Infusion[]
  disabled?: boolean
  onChartRetrospective: (minute: number) => void
}

type Run = { entries: LogEntry[] }

/** Consecutive auto-charted (multi-step) entries collapse into one run; anything else is its own run. */
function groupIntoRuns(titrations: LogEntry[]): Run[] {
  const runs: Run[] = []
  let i = 0
  while (i < titrations.length) {
    const entry = titrations[i]
    if (entry.autoGeneratedByMultiStep) {
      const batch = [entry]
      let j = i + 1
      while (j < titrations.length && titrations[j].autoGeneratedByMultiStep) {
        batch.push(titrations[j])
        j++
      }
      runs.push({ entries: batch })
      i = j
    } else {
      runs.push({ entries: [entry] })
      i++
    }
  }
  return runs
}

/**
 * A nurse who's been busy titrating doesn't always chart in the moment — this lets
 * them pick a past titration's minute and backdate a chart entry to it. Vitals are
 * auto-filled from vitalsHistory (what genuinely happened then), never freely
 * entered — this isn't testing recall, just giving a better way to see when each
 * titration happened and catch up on documentation for it.
 *
 * Consecutive auto-charted (multi-step) titrations (a single "Apply these steps" click
 * can generate dozens) collapse into one summary row rather than one row apiece,
 * DEFAULT COLLAPSED — a long run made this list unmanageably tall to scroll. Expanding
 * it reveals each step's own already-charted vitals.
 *
 * Every auto-charted step is charted for its OWN moment the instant it's generated, so
 * that part never needs a star. But CP 4-156 also requires a SEPARATE follow-up chart
 * ~30 min after each titration — auto-charting doesn't (and shouldn't) reach 30
 * minutes into the future, so an auto-charted step deep in a long run can still have a real,
 * outstanding "+30 min after this titration" gap once the run ends. That still gets a
 * star (on the step, and aggregated onto the collapsed batch header so it's visible
 * without expanding) even though the step itself already reads "Charted" — the two
 * facts aren't in conflict, they're different checkpoints. Reuses the same
 * buildCadenceStatusForOrders data the live Charting Status panel and the pre-end
 * warning already draw from, so a gap is visible right here as it happens instead of
 * only surfacing in a long list at the very end of the session.
 */
export function TitrationTimeline({
  log,
  vitalsHistory,
  orders,
  infusions,
  disabled,
  onChartRetrospective,
}: TitrationTimelineProps) {
  const [openKey, setOpenKey] = useState<string | null>(null)

  const titrations = log
    .filter((e) => e.type === 'action' && e.doseAction != null && e.outcome === 'applied')
    .sort((a, b) => a.minute - b.minute)

  const chartedMinutes = new Set(
    log.filter((e) => e.type === 'documentation' && e.location === 'iView').map((e) => e.minute),
  )
  const chartedVitalsAtMinute = new Map(
    log
      .filter((e) => e.type === 'documentation' && e.location === 'iView' && e.vitalsSnapshot)
      .map((e) => [e.minute, e.vitalsSnapshot!] as const),
  )

  const doseEntries = log.filter((e) => e.type === 'action' && e.doseAction != null)
  const cadenceByOrder = new Map(
    buildCadenceStatusForOrders(orders, infusions, doseEntries, [...chartedMinutes]).map((s) => [s.orderId, s]),
  )
  const titrationIndexByEntryId = new Map<string, number>()
  for (const order of orders) {
    doseEntries
      .filter((e) => e.orderId === order.id && e.doseAction === 'titrate' && e.outcome === 'applied')
      .sort((a, b) => a.minute - b.minute)
      .forEach((e, idx) => titrationIndexByEntryId.set(e.id, idx + 1))
  }

  function isFlagged(entry: LogEntry): boolean {
    const status = entry.orderId ? cadenceByOrder.get(entry.orderId) : undefined
    if (!status) return false
    if (entry.doseAction === 'initiate') {
      return status.checks.some((c) => (c.point === 'initiation' || c.point === 'plus30Start') && !c.met)
    }
    const titrationIndex = titrationIndexByEntryId.get(entry.id)
    return status.checks.some((c) => c.titrationIndex === titrationIndex && !c.met)
  }

  if (titrations.length === 0) {
    return (
      <Panel title="Titration timeline" subtitle="Times of each titration, for backdated charting">
        <p className="text-sm text-muted">No titrations yet this session.</p>
      </Panel>
    )
  }

  const vitalsAt = (minute: number) =>
    vitalsHistory.filter((h) => h.minute <= minute).reduce<{ minute: number; vitals: VitalSigns } | null>(
      (best, h) => (best == null || h.minute > best.minute ? h : best),
      null,
    )

  const runs = groupIntoRuns(titrations)

  return (
    <Panel title="Titration timeline" subtitle="Times of each titration, for backdated charting">
      <ul className="flex flex-col gap-2">
        {runs.map((run) =>
          run.entries.length === 1 ? (
            <SingleEntryRow
              key={run.entries[0].id}
              entry={run.entries[0]}
              isOpen={openKey === run.entries[0].id}
              onToggle={() => setOpenKey((k) => (k === run.entries[0].id ? null : run.entries[0].id))}
              historical={vitalsAt(run.entries[0].minute)}
              alreadyCharted={chartedMinutes.has(run.entries[0].minute)}
              flagged={isFlagged(run.entries[0])}
              disabled={disabled}
              onChartRetrospective={onChartRetrospective}
            />
          ) : (
            <AutoChartedBatchRow
              key={run.entries[0].id}
              entries={run.entries}
              isOpen={openKey === run.entries[0].id}
              onToggle={() => setOpenKey((k) => (k === run.entries[0].id ? null : run.entries[0].id))}
              chartedVitalsAtMinute={chartedVitalsAtMinute}
              isFlagged={isFlagged}
              disabled={disabled}
            />
          ),
        )}
      </ul>
    </Panel>
  )
}

function EntryLabel({ entry }: { entry: LogEntry }) {
  const drug = entry.drugId ? getDrug(entry.drugId) : null
  return (
    <span className="flex-1 text-ink">
      {entry.doseAction === 'initiate' ? 'Initiate' : 'Titrate'} {drug?.name ?? ''} to {entry.dose} {drug?.unit ?? ''}
    </span>
  )
}

function FlagStar({ title = 'Charting still needed for this titration' }: { title?: string }) {
  return (
    <span aria-hidden="true" className="text-warning" title={title}>
      ★
    </span>
  )
}

function SingleEntryRow({
  entry,
  isOpen,
  onToggle,
  historical,
  alreadyCharted,
  flagged,
  disabled,
  onChartRetrospective,
}: {
  entry: LogEntry
  isOpen: boolean
  onToggle: () => void
  historical: { minute: number; vitals: VitalSigns } | null
  alreadyCharted: boolean
  flagged: boolean
  disabled?: boolean
  onChartRetrospective: (minute: number) => void
}) {
  return (
    <li className={`rounded-md border ${flagged ? 'border-warning/40 bg-warning/5' : 'border-border'}`}>
      <button
        type="button"
        disabled={disabled}
        onClick={onToggle}
        className="flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm disabled:opacity-50"
      >
        <span className="font-mono text-muted">{formatClock(entry.minute)}</span>
        {flagged && <FlagStar />}
        <EntryLabel entry={entry} />
        <span aria-hidden="true" className="text-muted">
          {isOpen ? '▾' : '▸'}
        </span>
      </button>
      {isOpen && historical && (
        <div className="border-t border-border bg-bg px-3 py-3">
          <p className="text-xs font-semibold tracking-wide text-muted uppercase">Vitals at {formatClock(entry.minute)}</p>
          <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-sm sm:grid-cols-4">
            <Reading label="HR" value={String(historical.vitals.hr)} />
            <Reading label="BP" value={`${historical.vitals.sbp}/${historical.vitals.dbp}`} />
            <Reading label="MAP" value={String(historical.vitals.map)} />
            <Reading label="SpO2" value={String(historical.vitals.spo2)} />
          </dl>
          <div className="mt-3 flex items-center gap-2">
            {alreadyCharted ? (
              <button
                type="button"
                disabled
                className="inline-flex h-8 cursor-not-allowed items-center gap-1.5 rounded-md bg-border px-3 text-sm font-medium text-muted"
              >
                <span aria-hidden="true">✓</span>
                Charted
              </button>
            ) : (
              <Button size="sm" disabled={disabled} onClick={() => onChartRetrospective(entry.minute)}>
                Chart for this time
              </Button>
            )}
          </div>
        </div>
      )}
    </li>
  )
}

function AutoChartedBatchRow({
  entries,
  isOpen,
  onToggle,
  chartedVitalsAtMinute,
  isFlagged,
  disabled,
}: {
  entries: LogEntry[]
  isOpen: boolean
  onToggle: () => void
  chartedVitalsAtMinute: Map<number, VitalSigns>
  isFlagged: (entry: LogEntry) => boolean
  disabled?: boolean
}) {
  const drug = entries[0].drugId ? getDrug(entries[0].drugId) : null
  const first = entries[0]
  const last = entries[entries.length - 1]
  const anyFlagged = entries.some(isFlagged)
  const followUpTitle = "This titration's +30-min follow-up chart is still due (its own dose was already auto-charted)"

  return (
    <li className={`rounded-md border ${anyFlagged ? 'border-warning/40 bg-warning/5' : 'border-border'}`}>
      <button
        type="button"
        disabled={disabled}
        onClick={onToggle}
        className="flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm disabled:opacity-50"
      >
        <span className="font-mono text-muted">
          {formatClock(first.minute)}–{formatClock(last.minute)}
        </span>
        {anyFlagged && <FlagStar title={followUpTitle} />}
        <span className="flex-1 text-ink">
          {entries.length} auto-charted steps · {drug?.name ?? ''} to {first.dose} → {last.dose} {drug?.unit ?? ''}
        </span>
        <span aria-hidden="true" className="text-muted">
          {isOpen ? '▾' : '▸'}
        </span>
      </button>
      {isOpen && (
        <div className="border-t border-border bg-bg px-3 py-2">
          <ul className="flex flex-col divide-y divide-border">
            {entries.map((entry) => {
              const vitals = chartedVitalsAtMinute.get(entry.minute)
              const flagged = isFlagged(entry)
              return (
                <li key={entry.id} className="flex flex-wrap items-center gap-x-4 gap-y-1 py-1.5 text-sm">
                  <span className="font-mono text-muted">{formatClock(entry.minute)}</span>
                  {flagged && <FlagStar title={followUpTitle} />}
                  <span className="text-ink">
                    {entry.dose} {drug?.unit ?? ''}
                  </span>
                  {vitals && (
                    <span className="font-mono text-xs text-muted">
                      HR {vitals.hr} · BP {vitals.sbp}/{vitals.dbp} · MAP {vitals.map} · SpO2 {vitals.spo2}
                    </span>
                  )}
                  <span className="ml-auto inline-flex items-center gap-1 text-xs font-medium text-muted">
                    <span aria-hidden="true">✓</span>
                    Charted
                  </span>
                </li>
              )
            })}
          </ul>
        </div>
      )}
    </li>
  )
}

function Reading({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs text-muted">{label}</dt>
      <dd className="font-mono text-ink">{value}</dd>
    </div>
  )
}
