import { useState } from 'react'
import { cerner } from '../../design/deviceTokens'
import { DeviceStatusBadge } from '../shared'
import { getDrug } from '../../data/formulary'
import { groupIntoRuns } from '../../engine/logGrouping'
import { formatClock } from '../../lib/time'
import type { LogEntry } from '../../state/types'

export interface DocumentationReviewProps {
  log: LogEntry[]
}

/**
 * Faithful (not stylized) Cerner-style chart review — the full session log, chronological.
 * Debrief-only: this is retrospective, so (unlike the live iView) it's fine to show
 * everything, including which entries were actions vs. documentation.
 *
 * A single "Apply these steps" click can generate dozens of paired action+documentation
 * rows (one pair per auto-charted step) — flattened chronologically those clutter this
 * table and read as if a nurse individually charted and acted on each one. Consecutive
 * autoGeneratedByMultiStep entries (regardless of action/documentation type) collapse
 * into one "Trend" summary row instead, default-collapsed; expanding it reveals the
 * individual steps exactly as they'd have rendered before this grouping existed. Every
 * other entry — anything not part of such a run — still renders as its own normal row.
 */
export function DocumentationReview({ log }: DocumentationReviewProps) {
  const [openKey, setOpenKey] = useState<string | null>(null)
  const sorted = [...log].sort((a, b) => a.minute - b.minute)
  const runs = groupIntoRuns(sorted)

  return (
    <div className="overflow-hidden rounded-md border" style={{ borderColor: cerner.gridLine }}>
      <div
        className="px-3 py-2 text-sm font-semibold"
        style={{ backgroundColor: cerner.chrome, color: cerner.chromeText }}
      >
        Documentation Review
      </div>
      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-sm" style={{ color: cerner.ink }}>
          <thead>
            <tr style={{ backgroundColor: cerner.surfaceAlt }}>
              {['Time', 'Type', 'Location', 'Entry'].map((h) => (
                <th
                  key={h}
                  className="border-b px-3 py-1.5 text-left text-xs font-semibold uppercase whitespace-nowrap"
                  style={{ borderColor: cerner.gridLine, color: cerner.muted }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {sorted.length === 0 ? (
              <tr>
                <td colSpan={4} className="px-3 py-4 text-center" style={{ color: cerner.muted }}>
                  No entries recorded this session.
                </td>
              </tr>
            ) : (
              runs.map((run, i) =>
                run.length === 1 ? (
                  <EntryRow
                    key={run[0].id}
                    entry={run[0]}
                    backgroundColor={i % 2 === 1 ? cerner.surfaceAlt : cerner.surface}
                  />
                ) : (
                  <AutoChartedBatchRows
                    key={run[0].id}
                    run={run}
                    backgroundColor={i % 2 === 1 ? cerner.surfaceAlt : cerner.surface}
                    isOpen={openKey === run[0].id}
                    onToggle={() => setOpenKey((k) => (k === run[0].id ? null : run[0].id))}
                  />
                ),
              )
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}

function EntryRow({
  entry,
  backgroundColor,
  indented,
}: {
  entry: LogEntry
  backgroundColor: string
  indented?: boolean
}) {
  return (
    <tr className="border-b last:border-0" style={{ borderColor: cerner.gridLine, backgroundColor }}>
      <td className={`py-2 font-mono whitespace-nowrap ${indented ? 'pl-8 pr-3' : 'px-3'}`}>{formatClock(entry.minute)}</td>
      <td className="px-3 py-2 whitespace-nowrap">
        <TypeBadge type={entry.type} />
      </td>
      <td className="px-3 py-2 whitespace-nowrap">{entry.location ?? '—'}</td>
      <td className="px-3 py-2">{entry.summary}</td>
    </tr>
  )
}

function TypeBadge({ type }: { type: LogEntry['type'] }) {
  const isDoc = type === 'documentation'
  return (
    <DeviceStatusBadge
      label={isDoc ? 'Documentation' : 'Action'}
      backgroundColor={isDoc ? cerner.completeBg : cerner.pendingBg}
      color={isDoc ? cerner.complete : cerner.pending}
    />
  )
}

/** Distinct from the Action/Documentation badges above — a batch is genuinely both, so
 *  neither label fits. Reuses the existing rateChangeBg/rateChangeText pairing (already
 *  used in CernerIView for rate-change highlighting), which reads as its own "this is a
 *  trend, not a single charted event" register rather than a new invented color. */
function TrendBadge() {
  return <DeviceStatusBadge label="Trend" backgroundColor={cerner.rateChangeBg} color={cerner.rateChangeText} />
}

/** Builds the collapsed row's one-sentence trend summary from the run's own data —
 *  no hard-coded clinical values. Dose trend comes from the run's dose-changing entries;
 *  vitals trend comes from its documentation entries that carry a vitalsSnapshot, and is
 *  only included when the MAP actually moved (otherwise it adds nothing worth reading). */
function summarizeRun(run: LogEntry[]): string {
  const parts: string[] = [`${run.length} auto-charted steps`]

  const doseEntries = run.filter((e) => e.doseAction != null)
  if (doseEntries.length > 0) {
    const first = doseEntries[0]
    const last = doseEntries[doseEntries.length - 1]
    const drug = first.drugId ? getDrug(first.drugId) : null
    if (drug) {
      parts.push(`${drug.name} ${first.dose} → ${last.dose} ${drug.unit}`)
    }
  }

  const vitalsEntries = run.filter((e) => e.type === 'documentation' && e.vitalsSnapshot)
  if (vitalsEntries.length > 0) {
    const firstVitals = vitalsEntries[0].vitalsSnapshot!
    const lastVitals = vitalsEntries[vitalsEntries.length - 1].vitalsSnapshot!
    if (firstVitals.map !== lastVitals.map) {
      parts.push(`MAP ${firstVitals.map} → ${lastVitals.map} mmHg, HR ${firstVitals.hr} → ${lastVitals.hr} bpm`)
    }
  }

  return parts.length > 1 ? `${parts[0]} — ${parts.slice(1).join(', ')}` : parts[0]
}

function AutoChartedBatchRows({
  run,
  backgroundColor,
  isOpen,
  onToggle,
}: {
  run: LogEntry[]
  backgroundColor: string
  isOpen: boolean
  onToggle: () => void
}) {
  const first = run[0]
  const last = run[run.length - 1]

  return (
    <>
      <tr className="border-b last:border-0" style={{ borderColor: cerner.gridLine, backgroundColor }}>
        <td className="px-3 py-2 font-mono whitespace-nowrap">
          {formatClock(first.minute)}–{formatClock(last.minute)}
        </td>
        <td className="px-3 py-2 whitespace-nowrap">
          <TrendBadge />
        </td>
        <td className="px-3 py-2 whitespace-nowrap">—</td>
        <td className="px-3 py-2">
          <button
            type="button"
            onClick={onToggle}
            className="flex w-full items-center gap-2 text-left"
            style={{ color: cerner.ink }}
          >
            <span className="flex-1">{summarizeRun(run)}</span>
            <span aria-hidden="true" style={{ color: cerner.muted }}>
              {isOpen ? '▾' : '▸'}
            </span>
          </button>
        </td>
      </tr>
      {isOpen &&
        run.map((entry) => <EntryRow key={entry.id} entry={entry} backgroundColor={cerner.surfaceAlt} indented />)}
    </>
  )
}
